#!/usr/bin/env sh
if ! head -1 "$1" | grep -qE "^DNWYF-[0-9]+ (feat|fix|docs|style|refactor|perf|test|workflow|build|ci|chore|revert)(\(.+?\))?: .{1,}$"
then
  echo "Aborting commit. Your commit message is invalid."
  exit 1
fi
if ! head -1 "$1" | grep -qE "^.{1,88}$"; then
  echo "Aborting commit. Your commit message is too long."
  exit 1
fi
